# Generated by Django 2.2.13 on 2020-08-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePkAndSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='', editable=False, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleUniqueSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comparator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_pk_and_slug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticlePkAndSlug')),
                ('article_unique_slug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleUniqueSlug')),
            ],
        ),
    ]
